### PR TITLE
Feature/2631 SCC Report Summary page

### PR DESCRIPTION
**Pull request by HalcyonJAC**
Closes https://github.com/jac-uk/admin/issues/2631

### CODE REVIEW

**Review by drieJAC — CHANGES_REQUESTED** [review]
Need some tests written for the permissions for these new callable functions please.
See the test/rules folder in DP.
Maybe some ones in test/actions too?

**Comment by KoWeiJAC** [comment]
> Need some tests written for the permissions for these new callable functions please. See the test/rules folder in DP. Maybe some ones in test/actions too?

@drieJAC 
I added tests for permissions and related helper functions.
Could you help to review it again ? Thanks !

**Review by drieJAC — CHANGES_REQUESTED** [review]
i think because you have added a new entry to firestore.rules you should add a test in the test/rules/3.exercises.spec.js file as well.
Give me a shout if you want me to show you.

**Comment by KoWeiJAC** [comment]
> i think because you have added a new entry to firestore.rules you should add a test in the test/rules/3.exercises.spec.js file as well. Give me a shout if you want me to show you.

@drieJAC I added the tests for firestore rules, could you help to review it again ? Thanks!

**Pull request merged**
