### PR TITLE
Admin #2322 Update Panel packs with latest working preferences

### PR DESCRIPTION
**Pull request by drieJAC**
**Description**
Added converter classes to handle different versions of the working prefs questions.
Outputs html for jurisdiction, location and additional working preferences questions. Updated the nodescript.

Closes jac-uk/admin#2322

### CODE REVIEW

**Review by HalcyonJAC — DISMISSED** [review]
#### Version 1
The "All Question Types" works for me.

#### Version 2
There are no working preferences in the export file.

https://github.com/jac-uk/digital-platform/assets/79906532/7e46971f-20ec-44f5-acd1-dfe0a1e8a71c

**Review by warrensearle — DISMISSED** [review]
Hey @drieJAC great to see you have included some tests!

One thing we need to be careful of is with regards version numbers... We already have an application form version number. You have introduced a version number for Working Preferences questions however this looks like it could easily get confused with the application (form) version. Could you amend the file and variable names to make it clearer that you are working with Working Preferences version number rather than application (form) version number.

e.g. the file `applicationConverterVersions` should perhaps be `workingPreferencesConverter`

**Comment by warrensearle** [comment]
Hey @drieJAC @HalcyonJAC 

I'm sticking my oar in!

I'm confused by the PR instructions. The changes in this PR won't have been deployed to develop (as they are in this PR) so I suspect the only way to test is to run the Admin UI against the local emulator (using this PR). Is that correct @drieJAC? If so please can you make this clearer in the test instructions.

@HalcyonJAC 

> There are no working preferences in the export file.

See above, I believe this will need to be tested using the local emulator (or maybe the nodeScript).
Alternatively the testing you are carrying out will need to wait until this PR has been merged - and could be recorded against the ticket itself, say.

**Comment by drieJAC** [comment]
Ok so the links in the description above are intended to be used once the code has been deployed to develop.
Ryan's tests were performed prior to that.
I have released the function to develop. @HalcyonJAC  and I tested it and the only issue was the order of the questions in Location Questions.
I will make the change that you suggest @warrensearle regarding 'applicationConverterVersions should perhaps be workingPreferencesConverter'

**Review by warrensearle — APPROVED** [review]
Good to see some tests 👍

**Pull request merged**
