### PR TITLE
#989/selection day timetable

### PR DESCRIPTION
**Pull request by tomlovesgithub**
bit of a smelly function to match candidates with selection day panels and assign them slots. 
Returns a timetable and a list of the unassignable candidates. 

see the tests too, think ive probably missed something but hopefully the function covers whatever you can throw at it

### CODE REVIEW

**Review by warrensearle — COMMENTED** [review]
This is looking good @tomlovesgithub. Great to see some tests.

**Comment by nickaddy** [comment]
@tomlovesgithub Can this be closed or is it pending checking once the frontend is up and running?

**Review by warrensearle — APPROVED** [review]

**Comment by warrensearle** [comment]
> @tomlovesgithub Can this be closed or is it pending checking once the frontend is up and running?


Lets get this closed. Any refinements can be done when the front end is up and running

**Review by HalcyonJAC — APPROVED** [review]
The tests look great to me.

**Pull request merged**
